services:
  postgres:
    ports:
      - "127.0.0.1:5432:5432"
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G

  redis:
    ports:
      - "127.0.0.1:6379:6379"

  sentinel-1:
    ports:
      - "127.0.0.1:26379:26379"

  sentinel-2:
    ports:
      - "127.0.0.1:26380:26379"

  sentinel-3:
    ports:
      - "127.0.0.1:26381:26379"
