port 26379
sentinel monitor promtx-master promtx-redis-master 6379 2
sentinel auth-pass promtx-master redis
sentinel down-after-milliseconds promtx-master 5000
sentinel failover-timeout promtx-master 10000
sentinel parallel-syncs promtx-master 1
